FROM oven/bun:latest AS base

WORKDIR /user/src/app

FROM base AS install
RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production

FROM base AS prerelease
COPY --from=install /temp/prod/node_modules node_modules
COPY . .
ENV NODE_ENV=production

FROM base AS release
COPY --from=install /temp/prod/node_modules node_modules
COPY --from=prerelease /user/src/app/ .
COPY --from=prerelease /user/src/app/package.json .

USER bun
EXPOSE 3000
CMD [ "bun", "run", "src/index.ts" ]