name: publish_client
on:
    [workflow_dispatch]
jobs:
  publish:
    name: publish client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: login to DOCKER HUB
          uses: docker/login-action@v3
          with: 
            username: ${{ secrets.DOCKER_USER_NAME }}
            password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
        - name: build surver docker image
          run: docker build -t ${{ secrets.DOCKER_USER_NAME }}/sih_client:latest .
        - name: push server docker image
          run: docker push ${{ secrets.DOCKER_USER_NAME }}/sih_client:latest     